version: '0.2'
phases:
  install:
    runtime-versions:
      nodejs: 20.13.1
  build:
    commands:
      - npm install
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: 'build'